import type { Exercise } from '@muscleos/types';

import catalog from './exerciseCatalog.json';
import demoIds from './exerciseDemos.json';

/**
 * Published catalog rows (generated from apps/mobile/src/data/exercises.ts by
 * generate-exercise-catalog.mjs) and the ids with an animated demo (generated by
 * scripts/build-exercise-animations.mjs).
 */
export type CatalogExercise = Pick<Exercise, 'id' | 'name' | 'muscles' | 'equipment' | 'category' | 'instructions'>;

export { categoryLabel, equipmentLine, filterExercises, muscleLine, typeLine } from './exerciseText';

export const EXERCISES = (catalog as CatalogExercise[]).slice().sort((a, b) => a.name.localeCompare(b.name));

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));
const DEMO_IDS = new Set<string>(demoIds);

export function getExercise(id: string): CatalogExercise | undefined {
  return BY_ID.get(id);
}

export function hasDemo(id: string): boolean {
  return DEMO_IDS.has(id);
}

/** Exercises with an animated demo, A–Z. */
export const DEMO_EXERCISES = EXERCISES.filter((e) => hasDemo(e.id));

export type DemoTheme = 'dark' | 'light';
export type DemoSources = Record<DemoTheme, { video: string; poster: string }>;

/** Clip and poster per site theme; rendered to sit on that theme's card colour. */
export function demoSources(id: string): DemoSources | undefined {
  if (!hasDemo(id)) return undefined;
  const files = (theme: DemoTheme) => ({
    video: `/exercise-demos/${id}-${theme}.mp4`,
    poster: `/exercise-demos/${id}-${theme}.webp`,
  });
  return { dark: files('dark'), light: files('light') };
}

export function exercisePath(id: string): string {
  return `/exercises/${id}`;
}

/** Up to `limit` other exercises that share this one's main muscle, demos first. */
export function relatedExercises(id: string, limit = 6): CatalogExercise[] {
  const self = getExercise(id);
  if (!self) return [];
  const main = self.muscles[0];
  return EXERCISES.filter((e) => e.id !== id && e.muscles.includes(main))
    .sort((a, b) => Number(hasDemo(b.id)) - Number(hasDemo(a.id)))
    .slice(0, limit);
}

/** The demo licence. The animations are MuscleOS originals released to the public domain. */
export const DEMO_LICENSE = {
  name: 'CC0 1.0',
  url: 'https://creativecommons.org/publicdomain/zero/1.0/',
} as const;
