/**
 * Catalog exercises with an animated demo on muscleos.app/exercises/<id>. Generated by
 * apps/landing/scripts/build-exercise-animations.mjs — do not edit by hand. The clips
 * themselves stay on the website; the app only links to them.
 */
export const EXERCISE_DEMO_IDS: readonly string[] = ['barbell-curl', 'barbell-row', 'bench-press', 'bulgarian-split', 'calf-raise', 'deadlift', 'face-pull', 'hammer-curl', 'hip-thrust', 'incline-bench', 'lat-pulldown', 'lateral-raise', 'leg-curl', 'leg-extension', 'leg-press', 'overhead-press', 'plank', 'pull-up', 'romanian-deadlift', 'seated-row', 'skull-crusher', 'squat', 'tricep-pushdown'];
