-- Catalog instruction copy from apps/mobile/src/data/exercises.ts.
-- Generated by apps/mobile/scripts/generate-exercise-catalog.mjs --instructions-migration=20261009010000_catalog_instruction_steps
-- Bumps updated_at to now() only on rows whose text changes, so existing clients pull the new
-- copy via the catalog delta (updated_at > watermark) and re-running is a no-op.

update public.catalog_exercises as c
set
  instructions = v.instructions,
  updated_at = now()
from (values
  ('air-squat', 'Set your feet a little wider than your hips with toes turned slightly out
Sit your hips down and back while your knees track over your toes, keeping your chest up and heels planted
Go as low as you can hold that position, then drive through your whole foot to stand'),
  ('arnold-press', 'Sit or stand holding dumbbells at shoulder height, palms toward you
Press overhead and turn your palms forward as the weights rise, finishing with arms straight
Reverse the turn as you lower back to the start'),
  ('assisted-chin-up', 'Set the counterweight, kneel or stand on the pad, and take the bar with palms toward you at shoulder width
Pull your elbows down to your sides until your chin clears the bar
Lower slowly to straight arms without letting the pad bounce you up'),
  ('assisted-dips', 'Choose the counterweight, grip the handles and rest your knees or feet on the pad with arms locked out
Bend your elbows and lower until your upper arms are about level with the floor, keeping your shoulders down
Press back up to straight arms'),
  ('assisted-pull-up', 'Set the counterweight, place your knees or feet on the pad and grip the bar palms forward, slightly wider than your shoulders
Drive your elbows down toward your ribs until your chin passes the bar
Return under control to a full hang'),
  ('back-extension', 'Adjust the pad so it sits just below your hip crease and hook your heels under the rollers
Keeping your back neutral, hinge forward at the hips, then lift your torso until it lines up with your legs
Avoid arching past straight; hold a plate to your chest for extra load'),
  ('ball-slams', 'Stand with feet about hip-width apart holding a slam ball
Reach it overhead as you rise onto the balls of your feet, then throw it hard into the floor just in front of you, bending your hips and knees as you follow through
Pick it up with a flat back and go again'),
  ('band-external-shoulder-rotation', 'Anchor a band at elbow height and stand side-on, holding it in the hand farthest from the anchor
Keep that elbow bent to 90 degrees and pinned to your side
Rotate your forearm outward away from your body, then let it return slowly'),
  ('band-internal-shoulder-rotation', 'Anchor a band at elbow height and stand side-on, holding it in the hand nearest the anchor
With your elbow bent to 90 degrees and tucked against your ribs, rotate your forearm in across your stomach
Control the return'),
  ('band-pull-apart', 'Hold a light band at shoulder height with straight arms and hands about shoulder-width apart
Squeeze your shoulder blades and pull the band apart until it touches your chest
Let your hands come back together slowly'),
  ('band-assisted-bench-press', 'Hang a band from the top of the rack so it supports the bar near your chest
Lie on the bench with feet planted and shoulder blades pulled together, then unrack
Lower the bar to your lower chest and press it back up over your shoulders'),
  ('face-pull', 'Anchor a band around face height and hold it with an overhand grip, arms out in front
Pull toward your forehead, leading with your elbows high and wide, and rotate your hands back so they finish beside your ears
Return with control'),
  ('banded-hip-march', 'Loop a mini band around the middle of both feet and stand tall with your core braced
Drive one knee up to hip height against the band without leaning back
Lower it with control and alternate legs'),
  ('banded-muscle-up', 'Loop a band over the bar and place your knee or foot in it for assistance
Pull explosively toward your lower chest, then lean your chest over the bar and press down until your arms are straight
Lower back to a hang under control'),
  ('banded-side-kick', 'Put a mini band around your ankles and hold a support for balance
Standing tall on one leg, lift the other leg straight out to the side without tilting your torso
Bring it back in slowly and finish your reps before switching'),
  ('tricep-dips', 'Support yourself on parallel bars with straight arms and shoulders pulled down
Bend your elbows and lower with a slight forward lean until your upper arms are about parallel to the floor
Press back up to lockout'),
  ('bar-hang', 'Grip an overhead bar with both hands about shoulder-width apart and lift your feet so you hang freely
Keep your body still and breathe steadily for the set time
Step down before your grip gives out'),
  ('bar-muscle-up', 'Hang from the bar with a firm overhand grip
Swing slightly and pull the bar explosively toward your hips while leaning your shoulders over it
Once your chest is above the bar, press down to straight arms, then lower back under control'),
  ('barbell-curl', 'Stand holding a barbell with an underhand grip at shoulder width, arms straight
Curl the bar toward your shoulders while your elbows stay close to your sides
Lower it slowly without swinging your torso'),
  ('barbell-front-raise', 'Stand tall holding a barbell in front of your thighs with an overhand grip
Keeping your arms nearly straight, lift the bar to shoulder height
Lower slowly and avoid leaning back'),
  ('barbell-hack-squat', 'Stand in front of a barbell with the bar behind your calves
Squat down and grip it behind you, then drive through your feet to stand, keeping your chest up and the bar close to your legs
Lower it back down along the same path'),
  ('barbell-incline-triceps-extension', 'Lie on an incline bench holding a barbell or EZ bar over your shoulders with a narrow grip
Bend only at the elbows to lower the bar behind your head
Extend your arms back to the start'),
  ('barbell-lunge', 'With a barbell across your upper back, stand tall
Step forward and lower until both knees are bent to roughly 90 degrees, back knee just above the floor
Push through your front foot to return and alternate legs'),
  ('skull-crusher', 'Lie on a flat bench holding a barbell over your chest with a narrow grip
Keep your upper arms still and bend your elbows to lower the bar toward your forehead
Straighten your arms to press it back up'),
  ('barbell-rear-delt-row', 'Hinge forward with a flat back holding a barbell with a wide overhand grip
Row the bar toward your upper chest with elbows flared out to the sides
Lower it with control'),
  ('barbell-row', 'Hinge forward to about 45 degrees with a flat back and hold the bar just outside your knees
Pull it into your lower ribs, driving your elbows back
Lower it under control without standing up'),
  ('barbell-seated-calf-raise', 'Sit on a bench with the balls of your feet on a raised plate and a padded barbell across your lower thighs
Lower your heels for a stretch, then push up onto your toes as high as you can
Pause briefly before lowering'),
  ('shrug', 'Stand holding a barbell in front of your thighs with straight arms
Lift your shoulders straight up toward your ears and hold for a moment
Lower them fully without rolling your shoulders'),
  ('squat', 'Set the bar across your upper back, brace, and walk it out of the rack
Sit down between your hips with your knees tracking over your toes and your chest up
Drive back up through your whole foot to standing'),
  ('barbell-standing-calf-raise', 'Stand with a barbell on your upper back and the balls of your feet on a sturdy plate or step
Let your heels drop for a stretch, then rise onto your toes as high as possible
Lower slowly each rep'),
  ('barbell-standing-triceps-extension', 'Stand holding a barbell overhead with a narrow grip and arms straight
Bend at the elbows to lower the bar behind your head, keeping your upper arms close to your ears
Extend back to the top'),
  ('barbell-walking-lunges', 'With a barbell across your upper back, step forward into a lunge until your back knee nearly touches the floor
Drive up through your front foot and step straight into the next lunge on the other side
Keep your torso upright throughout'),
  ('wrist-curl', 'Sit with your forearms resting on your thighs or a bench, holding a barbell palms up with your wrists past the edge
Let the bar roll down toward your fingers, then curl your wrists up as far as you can
Keep your forearms still'),
  ('barbell-wrist-curl-behind-the-back', 'Stand holding a barbell behind your hips, palms facing back
Keep your arms straight and curl your wrists to lift the bar a few inches
Lower slowly and let the bar roll into your fingers for a full range'),
  ('barbell-wrist-extension', 'Rest your forearms on a bench or your thighs holding a barbell palms down, wrists hanging over the edge
Raise the back of your hands toward the ceiling, then lower slowly
Use a light weight; the range is small'),
  ('bayesian-curl', 'Set a cable handle low, face away from the stack and take a step forward so your arm is drawn slightly behind you
Curl the handle up while your elbow stays behind your torso
Lower slowly until your arm is straight again'),
  ('behind-the-neck-press', 'Sit or stand with a barbell resting on your upper back, hands just outside shoulder width
Press it straight up until your arms lock out overhead, then lower it behind your head to about ear level
Use only a range your shoulders tolerate comfortably'),
  ('belt-squats', 'Attach the belt around your hips and stand on the platform with feet about shoulder-width apart
Squat down with your torso upright, then drive through your feet to stand
Hold the handles only for balance'),
  ('bench-dip', 'Sit on the edge of a bench, place your hands beside your hips and slide your hips off with legs out in front
Bend your elbows to lower until your upper arms are about parallel to the floor
Press back up to straight arms, keeping your back close to the bench'),
  ('bench-press', 'Lie on the bench with your eyes under the bar, feet planted and shoulder blades squeezed together
Unrack, lower the bar to your mid-chest with elbows angled slightly in, then press it back up over your shoulders'),
  ('bicycle-crunch', 'Lie on your back with hands lightly behind your head and legs raised
Bring one knee in as you rotate the opposite elbow toward it while straightening the other leg
Alternate sides in a steady rhythm without pulling on your neck'),
  ('block-clean', 'Set the barbell on blocks at about knee height and grip it just outside your legs
Drive through your legs and extend your hips explosively, then pull yourself under to catch the bar on your shoulders in a front squat
Stand up to finish'),
  ('block-snatch', 'Place the barbell on blocks around knee height and take a wide snatch grip
Extend your hips and knees explosively, then pull under the bar and catch it overhead on straight arms in a squat
Stand up with the bar stable overhead'),
  ('board-press', 'Set up as for a bench press with a board or stack of boards on your chest, held by a partner or strapped in place
Lower the bar until it touches the board, pause briefly, and press back up to lockout'),
  ('bodyweight-curl', 'Hold a low bar, rings or suspension straps with palms up and lean back with straight arms and a rigid body
Curl your hands toward your forehead to pull your body up, keeping your elbows pointed forward
Lower yourself slowly'),
  ('bodyweight-leg-curl', 'Kneel or lie with your heels anchored and your body straight from knees to shoulders
Lower your torso forward slowly using your hamstrings, then pull yourself back up, using your hands to assist if needed
Keep your hips extended throughout'),
  ('body-weight-lunge', 'Stand tall with hands on your hips
Step forward and bend both knees until the back one hovers just above the floor
Push off the front foot to return and switch legs'),
  ('triceps-bodyweight-extension', 'Hold a bar or bench edge at about hip height and walk your feet back into a plank
Bend your elbows so your forehead moves toward your hands, keeping your body straight
Straighten your arms to push back up'),
  ('box-jump', 'Stand facing a sturdy box a short distance away
Swing your arms and jump up, landing softly on the box with both feet and bent knees
Stand up fully, then step down rather than jumping off'),
  ('box-squat', 'Set a box behind you at a height that puts you at or just below parallel
With the bar on your back, sit back until you are seated briefly on the box, staying tight
Drive up through your feet to stand'),
  ('bulgarian-split', 'Stand a stride in front of a bench and rest the top of your back foot on it
Lower straight down until your front thigh is about parallel to the floor
Push through your front foot to rise, and finish all reps before switching legs'),
  ('cable-chest-press', 'Set both cable handles at chest height and stand in a split stance facing away from the stack
Press the handles forward until your arms are straight and your hands meet in front of your chest
Bring them back slowly until you feel a stretch across your chest'),
  ('cable-crossover-bicep-curl', 'Stand between two high pulleys holding a handle in each hand, arms out to the sides at shoulder height with palms up
Curl both handles toward your head while your upper arms stay still
Straighten your arms slowly'),
  ('cable-crunch', 'Kneel facing a high pulley and hold a rope attachment beside your head
Keeping your hips still, curl your torso down to bring your elbows toward your thighs
Return slowly until your abs are stretched'),
  ('cable-curl-with-bar', 'Attach a straight bar to a low pulley and stand close with an underhand grip
Curl the bar toward your chest with elbows tucked at your sides
Lower it until your arms are straight'),
  ('cable-curl-with-rope', 'Attach a rope to a low pulley and hold it with thumbs up
Curl it toward your shoulders, keeping your elbows at your sides, and spread the ends slightly at the top
Lower with control'),
  ('cable-external-shoulder-rotation', 'Set a cable handle at elbow height and stand side-on, gripping it with the far hand
Keep your elbow bent at 90 degrees against your side and rotate your forearm out away from your body
Let it return slowly'),
  ('cable-front-raise', 'Stand facing away from a low pulley with the handle in one hand beside your thigh
Raise your arm in front of you to shoulder height with a slight bend in the elbow
Lower slowly'),
  ('cable-glute-kickback', 'Attach an ankle strap to a low pulley and face the stack, holding the frame for support
With a slight bend in your knee, drive the strapped leg straight back by squeezing your glute
Return without letting the weight stack touch down'),
  ('internal-shoulder-rotations', 'Set a cable handle at elbow height and stand side-on, gripping it with the near hand
With your elbow pinned at 90 degrees, rotate your forearm in across your body
Return slowly to the start'),
  ('cable-lateral-raise', 'Stand side-on to a low pulley and hold the handle in your far hand across your body
Raise your arm out to the side until it reaches shoulder height, leading with the elbow
Lower with control'),
  ('cable-machine-hip-abduction', 'Attach an ankle strap to a low pulley and stand side-on with the strap on your outside leg
Holding the frame for balance, lift that leg out to the side away from the machine
Bring it back in slowly'),
  ('cable-machine-hip-adduction', 'Attach an ankle strap to a low pulley and stand side-on with the strap on your inside leg
Holding the frame, sweep that leg across in front of your standing leg
Let it return out to the side with control'),
  ('cable-pull-through', 'Face away from a low pulley holding a rope between your legs and walk forward a couple of steps
Hinge at your hips so the rope travels back between your legs, keeping your back flat
Drive your hips forward to stand tall'),
  ('cable-rear-delt-row', 'Set a cable at shoulder height and hold a rope or handles with an overhand grip
Row toward your face with your elbows high and wide, squeezing the backs of your shoulders
Straighten your arms slowly'),
  ('cable-wide-grip-seated-row', 'Sit at a cable row station with feet braced and hold a wide bar with an overhand grip
Sit tall and pull the bar to your upper stomach, driving your elbows out and back
Let your arms extend fully before the next rep'),
  ('calf-raise-in-leg-press', 'Sit in the leg press and place the balls of your feet on the bottom edge of the platform with legs almost straight
Push the platform away by pointing your toes, then let it come back for a deep calf stretch
Keep the safety catches in reach and do not bend your knees'),
  ('heel-raise', 'Stand with the balls of your feet on a step, holding something for balance
Lower your heels below the step, then rise as high as you can onto your toes
Pause at the top before lowering'),
  ('captains-chair-knee-raise', 'Support yourself on the forearm pads with your back against the pad and legs hanging
Bring your knees up toward your chest by curling your pelvis
Lower your legs slowly without swinging'),
  ('captains-chair-leg-raise', 'Support yourself on the forearm pads with your back against the pad
Keeping your legs straight, raise them until they are at least level with your hips
Lower them slowly to the start'),
  ('chair-squats', 'Stand in front of a chair with feet shoulder-width apart
Sit back and down until you lightly touch the seat, keeping your weight in your heels
Stand straight back up without rocking forward'),
  ('chest-to-bar', 'Hang from a pull-up bar with an overhand grip
Pull hard enough that your chest touches the bar, driving your elbows down and back
Lower yourself under control to a full hang'),
  ('chest-supported-dumbbell-row', 'Set an incline bench to about 30–45 degrees and lie face down with a dumbbell in each hand
Row the dumbbells up to your sides, squeezing your shoulder blades together
Lower them until your arms are straight'),
  ('chinups', 'Hang from a bar with an underhand grip at about shoulder width
Pull your elbows down toward your ribs until your chin clears the bar
Lower yourself all the way to straight arms'),
  ('clamshells', 'Lie on your side with knees bent and heels stacked, adding a band above your knees if you like
Keeping your feet together, open your top knee as far as you can without rolling your hips back
Close it slowly'),
  ('clap-push-up', 'Start in a push-up position
Lower your chest, then push off the floor explosively so your hands leave the ground and clap once
Land with soft elbows and go straight into the next rep'),
  ('clean', 'Set up over the bar with feet under your hips and a grip just outside your legs
Lift it off the floor, extend explosively through your hips and knees, then pull yourself under to catch the bar on your shoulders in a front squat
Stand up to finish'),
  ('clean-and-jerk', 'Clean the bar from the floor to your shoulders and stand up
Dip and drive with your legs, then push yourself under the bar into a split or squat to catch it on locked arms
Bring your feet together and stand with the bar overhead'),
  ('close-grip-bench', 'Lie on the bench and grip the bar at about shoulder width
Lower it to your lower chest with elbows close to your body
Press back up, focusing on straightening your elbows'),
  ('close-grip-chin-up', 'Hang from a bar with an underhand grip, hands a few inches apart
Pull your chest toward the bar until your chin clears it
Lower to straight arms with control'),
  ('close-grip-feet-up-bench-press', 'Lie on the bench with your knees bent and feet lifted off the floor, gripping the bar at shoulder width
Lower it to your lower chest with elbows tucked
Press back up without twisting on the bench'),
  ('close-grip-lat-pulldown', 'Sit at the pulldown with thighs under the pads and hold a bar with a narrow grip
Pull it to your upper chest while leaning back slightly and driving your elbows down
Let it rise until your arms are straight'),
  ('close-grip-push-up', 'Get into a push-up with your hands directly under your shoulders or slightly closer
Lower your chest while keeping your elbows close to your ribs
Press back up with your body in one straight line'),
  ('cobra-push-up', 'Lie face down with hands under your shoulders and legs straight
Press your chest up by straightening your arms while your hips stay on the floor, then lower yourself back down
Move within a comfortable range for your lower back'),
  ('concentration-curl', 'Sit on a bench with a dumbbell in one hand and the back of that arm braced against your inner thigh
Curl the weight toward your shoulder without moving your upper arm
Lower it slowly to full extension'),
  ('copenhagen-plank', 'Lie on your side and rest your top leg on a bench, with the inside of your knee or ankle on the pad
Prop yourself up on your forearm and lift your hips so your body forms a straight line
Hold, then switch sides'),
  ('core-twist', 'Sit on the floor with knees bent, lean back slightly and hold a weight in front of your chest
Rotate your torso to bring the weight toward one hip, then the other
Keep your back long and move from your trunk rather than your arms'),
  ('cossack-squat', 'Take a very wide stance with toes turned slightly out
Shift your weight to one side and squat down over that leg while the other stays straight with its toes lifting
Push back up and alternate sides'),
  ('crossbody-cable-triceps-extension', 'Set two cables at a high position and stand between them, holding the left handle in your right hand and the right handle in your left hand
With your elbows bent in front of you, extend your arms out and down to the sides
Return slowly'),
  ('crunch', 'Lie on your back with knees bent and feet flat, hands on your chest or lightly at your head
Curl your shoulders off the floor by tightening your abs
Lower back down slowly'),
  ('cuban-press', 'Hold light dumbbells and raise your elbows out to shoulder height with forearms hanging
Rotate your forearms up until they point to the ceiling, then press the weights overhead
Reverse each step to lower'),
  ('curtsy-lunge', 'Stand tall with hands on your hips
Step one leg diagonally behind and across the other, then bend both knees to lower
Push through the front foot to stand and alternate sides'),
  ('dead-bugs', 'Lie on your back with arms reaching toward the ceiling and knees bent at 90 degrees over your hips
Press your lower back into the floor and slowly extend one arm and the opposite leg
Bring them back and switch sides'),
  ('dead-bugs-with-dumbbells', 'Lie on your back holding a light dumbbell in each hand over your chest, knees bent above your hips
Keeping your lower back flat, lower one arm overhead and extend the opposite leg
Return and alternate'),
  ('deadlift', 'Stand with the bar over your mid-foot and grip it just outside your legs
Brace, flatten your back and push the floor away to stand up, keeping the bar close to your body
Hinge at your hips to lower it back to the floor'),
  ('death-march-with-dumbbells', 'Hold a dumbbell in each hand and take a short step forward
Hinge at the hips over your front leg with a soft knee and a flat back until you feel your hamstrings stretch
Stand up while stepping through and repeat on the other leg'),
  ('decline-bench-press', 'Secure your legs on a decline bench and lie back under the bar
Lower it to your lower chest with control, then press it up until your arms are straight
Use a spotter or safety arms'),
  ('decline-push-up', 'Place your feet on a bench or step and your hands on the floor slightly wider than your shoulders
Lower your chest toward the floor keeping your body straight
Push back up'),
  ('deficit-deadlift', 'Stand on a low platform or plate so the bar starts slightly lower than usual
Set a flat back, brace, and drive through your feet to lift the bar to standing
Lower it with control'),
  ('depth-jump', 'Stand on a low box
Step off, land on both feet and immediately jump as high as you can
Keep ground contact short and land softly with your knees tracking over your toes'),
  ('devils-press', 'Start with a dumbbell in each hand on the floor
Drop into a burpee with your chest to the floor, jump your feet back in, then swing both dumbbells from between your legs up to overhead in one motion
Lower them and repeat'),
  ('donkey-calf-raises', 'Bend forward at the hips with your hands on a support and the balls of your feet on a raised edge, with load on your hips from a machine pad or belt
Drop your heels for a stretch, then rise onto your toes as high as you can
Keep your knees nearly straight'),
  ('donkey-kicks', 'Start on all fours with hands under shoulders and knees under hips
Keeping one knee bent at 90 degrees, press that foot up toward the ceiling until your thigh lines up with your torso
Lower without arching your lower back and finish one side before switching'),
  ('drag-curl', 'Stand holding a barbell with an underhand grip
Curl it up by pulling your elbows back so the bar slides up close to your body toward your lower chest
Lower it along the same path'),
  ('dragon-flag', 'Lie on a bench and grip it behind your head
Lift your hips and legs until your body is straight and resting on your upper back, then lower it slowly as one rigid unit without bending at the hips
Stop before your lower back touches and raise again'),
  ('dumbbell-fly', 'Lie on a flat bench with dumbbells above your chest, palms facing each other and elbows slightly bent
Open your arms wide in an arc until you feel a stretch across your chest
Bring the weights back together over your chest using the same arc'),
  ('dumbbell-chest-press', 'Lie on a flat bench holding a dumbbell at each side of your chest
Press them up until your arms are straight above your shoulders
Lower slowly back to chest level'),
  ('dumbbell-curl', 'Stand with a dumbbell in each hand at your sides, palms forward
Curl the weights toward your shoulders with your elbows staying by your ribs
Lower them fully without swinging'),
  ('dumbbell-deadlift', 'Stand with a dumbbell in each hand in front of your thighs or at your sides
Push your hips back and bend your knees to lower the weights to about mid-shin with a flat back
Drive through your feet to stand tall'),
  ('dumbbell-decline-chest-press', 'Secure your legs on a decline bench and lie back with a dumbbell beside each side of your chest
Press them up until your arms are straight
Lower under control'),
  ('dumbbell-floor-press', 'Lie on the floor with knees bent, holding dumbbells above your chest
Lower until your upper arms rest lightly on the floor, then press back up to straight arms'),
  ('dumbbell-frog-pumps', 'Lie on your back with the soles of your feet together and knees falling out, resting a dumbbell on your hips
Push through the outer edges of your feet to lift your hips, squeezing your glutes at the top
Lower and repeat at a steady pace'),
  ('front-raise', 'Stand with dumbbells in front of your thighs
Raise one or both arms forward to shoulder height with a slight bend in the elbow
Lower slowly without leaning back'),
  ('lying-dumbbell-external-shoulder-rotation', 'Lie face down on a bench with your upper arm out to the side at shoulder level and your elbow bent so the dumbbell hangs toward the floor
Keeping your elbow in place, rotate your forearm forward and up until it is about level with the bench
Lower slowly
Use a light weight'),
  ('dumbbell-horizontal-internal-shoulder-rotation', 'Lie on your back with your upper arm out to the side on the floor and your elbow bent at 90 degrees, forearm resting back toward your head
Rotate the dumbbell forward until your forearm points at the ceiling
Return slowly
Keep the weight light'),
  ('lateral-raise', 'Stand holding dumbbells at your sides with a slight bend in your elbows
Raise your arms out to the sides until they reach shoulder height
Lower slowly without shrugging'),
  ('lunges', 'Stand holding a dumbbell in each hand at your sides
Step forward and lower until your back knee is just above the floor
Press through your front foot to return and switch legs'),
  ('lying-dumbbell-internal-shoulder-rotation', 'Lie on your side on a bench, on the arm you are training, with the upper arm resting on the bench and elbow bent at 90 degrees
Rotate your forearm up toward your stomach while the elbow stays put
Lower slowly
Use a light weight'),
  ('dumbbell-lying-triceps-extension', 'Lie on a flat bench holding dumbbells over your chest with palms facing each other
Bend at the elbows to lower the weights beside your head, keeping your upper arms still
Straighten your arms to return'),
  ('dumbbell-preacher-curl', 'Sit at a preacher bench with the back of your upper arm flat on the pad, holding a dumbbell
Curl it up toward your shoulder, then lower until your arm is almost straight
Stay controlled at the bottom'),
  ('dumbbell-pullover', 'Lie across or along a bench holding one dumbbell with both hands over your chest
With a slight bend in your elbows, lower it back over your head until you feel a stretch in your lats and chest
Pull it back over your chest'),
  ('dumbbell-rear-delt-row', 'Hinge forward with a flat back or lie chest-down on an incline bench, holding dumbbells
Row them out to the sides with your elbows flared wide so your upper arms finish level with your shoulders
Lower slowly'),
  ('dumbbell-romanian-deadlift', 'Stand holding dumbbells in front of your thighs with soft knees
Push your hips back and slide the weights down your legs until you feel your hamstrings stretch, keeping your back flat
Squeeze your glutes to stand up'),
  ('dumbbell-row', 'Put one knee and hand on a bench with your back flat, holding a dumbbell in the other hand
Row it toward your hip, keeping your elbow close to your body
Lower until your arm is straight'),
  ('dumbbell-shrug', 'Stand with a dumbbell in each hand at your sides
Lift your shoulders straight up toward your ears and pause
Lower them all the way down'),
  ('side-bend', 'Stand tall with a dumbbell in one hand at your side
Bend sideways toward the weight, then use your opposite side to pull back up to upright and a little past
Finish your reps and switch hands'),
  ('dumbbell-squat', 'Stand holding dumbbells at your sides with feet about shoulder-width apart
Squat down with your chest up until your thighs are about parallel
Drive back up through your feet'),
  ('dumbbell-standing-triceps-extension', 'Stand holding one dumbbell overhead with both hands under the top plate
Lower it behind your head by bending your elbows, keeping your upper arms near your ears
Extend back to the top'),
  ('dumbbell-walking-lunge', 'Hold a dumbbell in each hand and step forward into a lunge
Drive through your front foot and bring your back leg straight through into the next step
Keep your torso tall and steps even'),
  ('dumbbell-wrist-curl', 'Sit with your forearm on your thigh or a bench, palm up and wrist over the edge, holding a dumbbell
Let it roll toward your fingertips, then curl your wrist up
Keep your forearm still'),
  ('reverse-wrist-curl', 'Rest your forearm on a bench or your thigh with your palm down and wrist past the edge, holding a dumbbell
Lift the back of your hand up, then lower slowly
Use a light weight'),
  ('dynamic-side-plank', 'Set up in a side plank on your forearm with your body in a straight line
Lower your hips a few inches toward the floor, then lift them back into line
Finish your reps and switch sides'),
  ('eccentric-heel-drop', 'Stand on a step on the balls of both feet, holding a support
Rise up on both feet, then lift one foot and slowly lower the heel of the other below the step
Use both feet to come back up'),
  ('lying-triceps-extension-ez-bar', 'Lie on a flat bench holding an EZ bar over your chest with a narrow grip
Bend your elbows to lower the bar toward your forehead while your upper arms stay fixed
Straighten your arms to return'),
  ('ez-curl', 'Stand holding an EZ bar on the angled underhand grips
Curl it toward your shoulders with elbows at your sides
Lower it slowly to straight arms'),
  ('farmers-walk', 'Pick up a heavy dumbbell, kettlebell or handle in each hand
Stand tall with your shoulders back and walk with short, steady steps
Set the weights down with a flat back when done'),
  ('feet-up-bench-press', 'Lie on the bench with your knees bent and feet raised off the floor
Grip the bar, lower it to your mid-chest, and press back up
Keep your body steady without leg drive'),
  ('fire-hydrants', 'Start on all fours
Keeping your knee bent, lift one leg out to the side until your thigh is about level with your hips
Lower it without shifting your weight and finish one side before switching'),
  ('floor-back-extension', 'Lie face down with your arms at your sides or hands by your head
Lift your chest a few inches off the floor using your lower back, keeping your neck in line
Lower slowly'),
  ('floor-press', 'Lie on the floor under a racked barbell with knees bent
Lower the bar until your upper arms touch the floor, pause briefly, then press it back up to lockout'),
  ('frog-pumps', 'Lie on your back with the soles of your feet together close to your hips and knees falling open
Push through the outer edges of your feet to lift your hips and squeeze your glutes
Lower and repeat quickly'),
  ('front-hold', 'Stand holding a weight plate with both hands
Raise it in front of you with straight arms to shoulder height and hold it there for the set time
Lower it with control'),
  ('front-squat', 'Rest the bar on the front of your shoulders with elbows pointing forward and high
Squat down with your torso upright until your thighs are at least parallel
Drive back up keeping your elbows up'),
  ('glute-bridge', 'Lie on your back with knees bent and feet flat near your hips
Push through your heels to lift your hips until your body is straight from shoulders to knees
Lower slowly'),
  ('glute-ham-raise', 'Set the foot plate so your knees sit just behind the pad and hook your heels in
Starting upright on your knees, lower your torso forward under control, then pull yourself back up with your hamstrings
Keep your hips straight'),
  ('goblet-squat', 'Hold a dumbbell or kettlebell vertically against your chest
Squat down between your knees with your chest up and elbows inside your knees
Stand back up through your whole foot'),
  ('good-morning', 'Place a barbell on your upper back and stand with soft knees
Push your hips back and lower your torso toward horizontal with a flat back
Drive your hips forward to stand
Start light'),
  ('gorilla-row', 'Stand in a wide stance hinged forward with two kettlebells or dumbbells on the floor between your feet
Row one up to your hip while pressing the other into the floor
Alternate sides with a flat back'),
  ('gripper', 'Hold a hand gripper with the handles across your palm and fingers
Squeeze until the handles touch, hold briefly, and release slowly
Train both hands'),
  ('ground-to-overhead', 'Stand over a weight plate, dumbbell or barbell with feet hip-width apart
Hinge down with a flat back, lift the weight to your shoulders, then press or push it overhead to straight arms
Lower it in stages back to the floor'),
  ('hack-squat', 'Stand on the machine platform with your back and shoulders against the pads and feet about shoulder-width apart
Release the safeties and lower until your thighs are about parallel
Push through your feet to rise'),
  ('half-body-weight-squats', 'Stand with feet about shoulder-width apart
Bend your hips and knees to squat about halfway down, keeping your chest up
Push back up to standing'),
  ('hammer-curl', 'Stand with dumbbells at your sides and palms facing in
Curl them toward your shoulders while keeping that neutral grip
Lower them slowly'),
  ('handstand-push-up', 'Kick up into a handstand against a wall with hands slightly wider than your shoulders
Lower your head toward the floor under control, then press back up to straight arms
Use a mat and build up with easier variations first'),
  ('hang-clean', 'Stand holding the bar at your hips, then lower it to just above your knees with a flat back
Jump explosively through your hips and knees and pull yourself under to catch the bar on your shoulders in a front squat
Stand up'),
  ('hang-power-clean', 'Hold the bar at your hips and slide it down to above your knees
Extend explosively and pull yourself under to catch the bar on your shoulders with your knees only slightly bent
Stand tall to finish'),
  ('hang-power-snatch', 'Hold the bar with a wide grip at your hips, then lower it to above your knees
Extend explosively and punch the bar overhead, catching it on locked arms in a partial squat
Stand up with it overhead'),
  ('hang-snatch', 'Take a wide grip and hold the bar at your hips, then lower it to above your knees
Drive up explosively and pull yourself under, catching the bar overhead in a full squat
Stand up with the bar stable'),
  ('hanging-knee-raise', 'Hang from a bar with straight arms
Bring your knees up toward your chest by curling your pelvis, avoiding a swing
Lower slowly'),
  ('hanging-leg-raise', 'Hang from a bar with straight arms and legs together
Keep your legs straight and raise them to at least hip height
Lower them under control without swinging'),
  ('hanging-sit-up', 'Hang upside down with your knees hooked over a bar or with gravity boots
Curl your torso up toward your knees, then lower slowly
Only attempt this with secure foot or knee support'),
  ('hanging-windshield-wiper', 'Hang from a bar and raise your legs straight up toward it
Rotate your legs to one side, back through the middle and to the other side
Keep the movement slow and controlled'),
  ('heel-walks', 'Lift your toes and balls of your feet off the floor so you are standing on your heels
Walk forward in short steps while keeping your toes up
Stand tall throughout'),
  ('high-to-low-wood-chop-with-band', 'Anchor a band high and stand side-on, holding it with both hands above your shoulder
Pull it down and across your body toward the opposite hip, rotating through your torso and pivoting your back foot
Return slowly'),
  ('cable-machine-wood-chop-high-to-low', 'Set a cable high and stand side-on, holding the handle with both hands above your shoulder
Pull it diagonally down across your body toward your opposite hip, turning through your trunk
Let it return with control'),
  ('hip-abductor', 'Sit in the machine with the pads on the outside of your knees
Push your legs outward as far as you comfortably can
Let them come back together slowly without the weight stack touching'),
  ('hip-abduction-against-band', 'Sit or lie with a mini band just above your knees
Press your knees out against the band, pause, and return slowly
Keep your feet together'),
  ('hip-adduction-against-band', 'Anchor a band low and loop it around the ankle nearest the anchor
Standing side-on, sweep that leg in across the front of your standing leg
Return slowly and switch sides'),
  ('hip-adductor', 'Sit in the machine with the pads on the inside of your knees and legs spread
Squeeze your legs together
Let them open back out slowly'),
  ('hip-thrust', 'Sit with your upper back against a bench and a padded barbell over your hips, feet flat
Drive through your heels to lift your hips until your body is flat from shoulders to knees
Lower until your hips are just off the floor'),
  ('hip-thrust-machine', 'Sit in the machine with your upper back on the pad and the belt or pad across your hips
Push through your heels to extend your hips fully, squeezing your glutes
Lower slowly'),
  ('hip-thrust-with-band-around-knees', 'Set up for a hip thrust with a mini band just above your knees
Press your knees out against the band as you drive your hips up
Lower slowly while keeping tension on the band'),
  ('hollow-body-crunch', 'Lie on your back with arms overhead and legs extended, lifting both slightly off the floor with your lower back pressed down
Crunch in by bringing your knees and chest together
Extend back to the hollow position without touching down'),
  ('hollow-hold', 'Lie on your back, press your lower back into the floor and lift your shoulders and straight legs a few inches off the ground
Reach your arms overhead or toward your feet
Hold the position for time'),
  ('horizontal-wood-chop-with-band', 'Anchor a band at chest height and stand side-on, holding it with both hands in front of your chest
Rotate your torso away from the anchor, keeping your arms extended
Return slowly'),
  ('horizontal-wood-chop-with-cable', 'Set a cable at chest height and stand side-on, holding the handle with both hands at arm''s length
Turn your torso away from the machine with your hips facing forward
Come back slowly'),
  ('fat-bar-deadlift', 'Set up as for a regular deadlift using a thick bar or grip sleeves
Grip hard, brace and stand up with the bar close to your legs
Lower it with a flat back'),
  ('reverse-cable-fly', 'Set two cables at shoulder height and grab the opposite handles with arms crossed in front of you
Pull your arms out wide with a slight bend in the elbows until they line up with your shoulders
Return slowly'),
  ('incline-bench', 'Set the bench to about 30–45 degrees and lie back with feet planted
Lower the bar to your upper chest, then press it up over your shoulders'),
  ('incline-dumbbell-curl', 'Sit back on an incline bench with arms hanging straight down, holding dumbbells
Curl them up without letting your elbows drift forward
Lower until your arms are fully straight'),
  ('dumbbell-incline-press', 'Set a bench to about 30–45 degrees and lie back with dumbbells at your upper chest
Press them up until your arms are straight
Lower slowly'),
  ('incline-push-up', 'Put your hands on a bench or box slightly wider than your shoulders and step back into a straight plank
Lower your chest to the edge, then push away
The higher the surface, the easier it is'),
  ('inverted-row', 'Lie under a bar set around waist height and grip it overhand
With your heels on the floor and body straight, pull your chest to the bar
Lower until your arms are straight'),
  ('inverted-row-with-underhand-grip', 'Lie under a bar at about waist height and grip it palms toward you
Keep your body straight and pull your chest up to the bar
Lower with control'),
  ('jackknife-sit-up', 'Lie on your back with arms overhead and legs straight
Lift your arms and legs at the same time so your hands reach toward your feet
Lower both slowly'),
  ('jefferson-curl', 'Stand on a raised platform holding a light weight
Tuck your chin and roll down one vertebra at a time, letting the weight travel down your legs
Roll back up slowly
Use very light loads and progress gradually'),
  ('jerk', 'Start with the bar across the front of your shoulders
Dip slightly, drive hard with your legs and push yourself under the bar, catching it on locked arms
Recover to standing with the bar overhead'),
  ('jump-squat', 'Stand with feet about shoulder-width apart
Drop into a quarter to half squat, then jump as high as you can
Land softly and go straight into the next rep'),
  ('jumping-lunges', 'Start in a lunge
Jump up and switch legs in the air, landing in a lunge with the other foot forward
Land softly and keep your torso upright'),
  ('jumping-muscle-up', 'Stand under a low bar and grip it overhand
Jump to help pull yourself over the bar, then press down to straight arms
Lower back to the floor with control'),
  ('kettlebell-clean', 'Stand over a kettlebell, hinge down and grip it with one hand
Hike it back, then drive your hips forward and guide it up so it rolls around your wrist into the rack position at your shoulder
Lower it the same way'),
  ('kettlebell-clean-and-jerk', 'Clean the kettlebell to the rack position
Dip and drive with your legs to send it overhead, dropping under it to lock out your arm
Stand tall, then lower to the rack'),
  ('kettlebell-clean-and-press', 'Clean the kettlebell to your shoulder
Brace and press it straight overhead without using your legs
Lower it back to the rack, then to the floor'),
  ('kettlebell-curl', 'Stand holding a kettlebell by the handle in one or both hands
Curl it toward your shoulder with your elbow tucked
Lower slowly'),
  ('kettlebell-floor-press', 'Lie on the floor with knees bent and a kettlebell in each hand, upper arms on the floor
Press the kettlebells up until your arms are straight
Lower until your elbows touch down'),
  ('kettlebell-front-squat', 'Hold one or two kettlebells in the rack position at your shoulders
Squat down with your chest up and elbows in
Drive up through your feet'),
  ('kettlebell-halo', 'Hold a kettlebell upside down by the horns at chest height
Circle it around your head, keeping it close and your core tight
Reverse direction each set'),
  ('kettlebell-plank-pull-through', 'Get into a high plank with a kettlebell just behind one hand
Reach under your body with the opposite hand and drag it to the other side
Alternate hands without letting your hips rotate'),
  ('kettlebell-press', 'Clean a kettlebell to the rack position
Brace and press it overhead until your arm is straight
Lower it back to your shoulder slowly'),
  ('kettlebell-push-press', 'Hold a kettlebell in the rack position
Dip your knees slightly and drive up, using that momentum to press the kettlebell overhead
Lower it to your shoulder'),
  ('kettlebell-row', 'Hinge forward with a flat back, bracing your free hand on a bench or your knee
Row the kettlebell toward your hip, keeping your elbow close
Lower until your arm is straight'),
  ('kettlebell-snatch', 'Hike the kettlebell back between your legs, then drive your hips forward and pull it up in one path to overhead
Punch your hand through as it flips over so it lands softly on your forearm with your arm locked
Bring it back down and into the next hike'),
  ('kettlebell-swing', 'Stand with feet a little wider than hip-width and the kettlebell slightly in front
Hike it back between your legs, then snap your hips forward to float it up to about chest height with straight arms
Let it fall back into the next hinge'),
  ('kettlebell-thrusters', 'Hold one or two kettlebells in the rack position
Squat down, then drive up hard and use that momentum to press the weights overhead
Lower them to your shoulders as you go into the next squat'),
  ('kettlebell-tibialis-raise', 'Sit on a high bench with your lower legs hanging and a light kettlebell hooked over the top of one foot
Pull your toes up toward your shin to lift the weight
Lower slowly and switch feet'),
  ('kettlebell-windmill', 'Press a kettlebell overhead with one arm and turn your feet about 45 degrees away from that side
Push your hips out toward the kettlebell and lower your free hand down your front leg, eyes on the weight
Return to upright with the arm locked'),
  ('kneeling-ab-wheel-roll-out', 'Kneel on a mat holding the ab wheel under your shoulders
Roll it forward slowly, keeping your hips in line and lower back from sagging
Go only as far as you can hold that position, then pull it back to your knees'),
  ('kneeling-incline-push-up', 'Place your hands on a bench or box and your knees on the floor behind you with a straight line from knees to head
Lower your chest to the edge, then press away'),
  ('kneeling-plank', 'Rest on your forearms and knees with your elbows under your shoulders
Tuck your hips so your body is straight from knees to head
Brace your abs and hold'),
  ('kneeling-push-up', 'Set your hands slightly wider than your shoulders and your knees on the floor behind you
Lower your chest toward the floor keeping a straight line from knees to head
Push back up'),
  ('kneeling-side-plank', 'Lie on your side with knees bent and prop yourself on your forearm
Lift your hips so your body is straight from knees to head
Hold, then switch sides'),
  ('kroc-row', 'Brace one hand on a bench or rack, feet staggered, holding a heavy dumbbell in the other
Row it toward your hip with some body English allowed, using straps if your grip limits you
Lower to a full stretch'),
  ('l-sit', 'Support yourself on parallel bars, dip handles or the floor with straight arms
Lift your legs straight out in front so your body forms an L
Hold with your shoulders pushed down'),
  ('landmine-hack-squat', 'Stand facing away from the landmine with the end of the bar held at your chest or shoulder
Lean back into it slightly and squat down with your knees traveling forward
Drive up through your feet'),
  ('landmine-press', 'Stand facing the landmine holding the end of the bar at your shoulder
Press it up and forward until your arm is straight
Lower it back to your shoulder'),
  ('landmine-rotation', 'Hold the end of the landmine bar with both hands, arms extended in front of your face
Rotate it down toward one hip, pivoting through your hips and back foot, then arc it over to the other side'),
  ('landmine-squat', 'Hold the end of a landmine bar against your chest with both hands
Squat down with your chest up and knees tracking over your toes
Stand back up'),
  ('lat-pulldown-with-neutral-grip', 'Attach a neutral-grip handle and sit with your thighs under the pads
Pull the handle to your upper chest, driving your elbows down and back
Let it return until your arms are straight'),
  ('lat-pulldown', 'Sit with your thighs under the pads and grip the bar overhand a little wider than your shoulders
Pull it to your upper chest with a slight lean back
Let it rise slowly to straight arms'),
  ('lat-pulldown-with-supinated-grip', 'Sit with your thighs under the pads and take an underhand grip at about shoulder width
Pull the bar to your upper chest with your elbows close
Return to straight arms'),
  ('lateral-bound', 'Stand on one leg
Jump sideways as far as you can and land on the opposite foot, absorbing the landing with a bent knee
Stabilize, then bound back'),
  ('lateral-walk-with-band', 'Put a mini band around your knees or ankles and sit into a quarter squat
Step sideways with one foot, then follow with the other while keeping tension on the band
Go both directions'),
  ('leg-curl-on-ball', 'Lie on your back with your heels on a stability ball and lift your hips
Curl your heels toward you by bending your knees, keeping your hips up
Roll the ball back out slowly'),
  ('leg-extension', 'Sit in the machine with the pad on your lower shins and knees aligned with the pivot
Straighten your legs fully
Lower slowly'),
  ('leg-press', 'Sit in the machine with your back against the pad and feet about shoulder-width on the platform
Release the safeties and lower until your knees are well bent, keeping your lower back on the pad
Press back up without locking out hard'),
  ('band-wood-chop-low-to-high', 'Anchor a band low and stand side-on, holding it with both hands near your outside knee
Pull it up and across your body to above the opposite shoulder, turning through your trunk
Return slowly'),
  ('cable-machine-wood-chop-low-to-high', 'Set a cable low and stand side-on, holding the handle with both hands near your knee
Pull it diagonally up across your body to above your opposite shoulder
Lower it with control'),
  ('lying-bicep-cable-curl-on-bench', 'Lie on a flat bench with your feet toward a low pulley, holding a bar attachment with an underhand grip
Keep your upper arms still and curl the bar toward your shoulders
Lower slowly'),
  ('lying-bicep-cable-curl-on-floor', 'Attach a straight bar to a low pulley and lie on your back with your feet toward the machine
Hold the bar underhand with arms extended by your hips
Curl it toward your shoulders keeping your elbows on the floor, then lower'),
  ('leg-curl', 'Lie face down on the machine with the pad just above your heels and knees just off the bench
Curl your heels toward your glutes
Lower slowly without letting your hips lift'),
  ('lying-leg-raise', 'Lie on your back with hands under your hips or at your sides
Keeping your legs straight, lift them until they point at the ceiling
Lower slowly with your lower back pressed down'),
  ('lying-neck-curl', 'Lie on your back on a bench with your head off the end, a folded towel and light plate on your forehead if needed
Tuck your chin and lift your head forward, then lower slowly
Use very light weight and move gently'),
  ('lying-neck-extension', 'Lie face down on a bench with your head off the end, a light plate on the back of your head if used
Lift your head up until it is in line with your spine, then lower slowly
Keep the load light'),
  ('lying-windshield-wiper', 'Lie on your back with arms out to the sides and straight legs raised to vertical
Lower your legs to one side without letting your shoulders lift, then bring them back through the middle to the other side'),
  ('lying-windshield-wiper-with-bent-knees', 'Lie on your back with arms out wide and knees bent over your hips
Rotate your knees down to one side, return to center and go to the other side
Keep your shoulders on the floor'),
  ('machine-bicep-curl', 'Sit in the machine with the backs of your upper arms on the pad and grip the handles
Curl them toward your shoulders
Lower slowly to nearly straight arms'),
  ('machine-chest-fly', 'Sit with your back on the pad and hold the handles with arms out to the sides and elbows slightly bent
Bring the handles together in front of your chest
Open back out slowly to a comfortable stretch'),
  ('machine-chest-press', 'Adjust the seat so the handles are at mid-chest height
Press them forward until your arms are straight
Return slowly'),
  ('machine-crunch', 'Sit in the machine, set the pads or handles and secure your feet
Curl your torso forward by contracting your abs
Return slowly'),
  ('machine-glute-kickbacks', 'Position yourself in the machine with the working foot on the platform or pad
Drive that leg back by extending your hip, squeezing your glute
Return slowly and switch legs after your reps'),
  ('machine-lat-pulldown', 'Adjust the seat and thigh pad, then grip the handles overhead
Pull them down toward your upper chest by driving your elbows down
Let them rise slowly'),
  ('machine-lateral-raise', 'Sit with the pads against the outside of your upper arms
Raise your arms out to the sides to shoulder height
Lower slowly'),
  ('machine-overhead-triceps-extension', 'Sit in the machine with your upper arms on the pad and elbows bent
Extend your arms until they are straight
Return slowly'),
  ('seated-machine-row', 'Adjust the seat and chest pad so the handles are at about chest height
Pull them toward your torso, squeezing your shoulder blades together
Let your arms straighten slowly'),
  ('machine-shoulder-press', 'Set the seat so the handles start around shoulder height
Press up until your arms are straight
Lower slowly'),
  ('medicine-ball-chest-pass', 'Stand facing a wall or partner holding a medicine ball at your chest
Step forward and push the ball away explosively with both hands
Catch it with soft arms and repeat'),
  ('military-press', 'Stand tall with your heels together and the bar at your front shoulders, hands just outside shoulder width
Squeeze your glutes and brace, then press the bar straight up without leaning back or bending your knees
Lock out overhead and lower under control to your shoulders'),
  ('monkey-row', 'Stand holding dumbbells in front of your thighs with a wide grip
Lead with your elbows to raise the weights up and out to the sides until your elbows reach shoulder height
Lower slowly'),
  ('mountain-climbers', 'Start in a high plank with hands under your shoulders
Drive one knee toward your chest, then quickly switch legs
Keep your hips level'),
  ('ring-muscle-up', 'Hang from rings with a false grip
Pull the rings to your lower chest, then lean your chest forward over your hands and press down until your arms are straight
Lower back to a hang under control'),
  ('neutral-close-grip-lat-pulldown', 'Attach a narrow neutral-grip handle and sit with your thighs under the pads
Pull it to your upper chest, keeping your elbows close
Let your arms extend fully'),
  ('nordic-hamstring-eccentric', 'Kneel with your ankles anchored under a pad or held by a partner
Keeping your hips straight, lower your torso forward as slowly as you can
Catch yourself with your hands and push back up'),
  ('oblique-crunch', 'Lie on your back with knees bent and let them fall to one side
With your hands lightly at your head, crunch your shoulders up toward the ceiling
Lower slowly and switch sides'),
  ('oblique-sit-up', 'Lie on your back with knees bent and feet anchored
Sit up while rotating your torso to bring one elbow toward the opposite knee
Lower and alternate sides'),
  ('one-legged-glute-bridge', 'Lie on your back with one knee bent and foot flat, the other leg lifted
Drive through the planted heel to lift your hips level
Lower and finish the set before switching'),
  ('one-arm-landmine-press', 'Stand in a split stance holding the end of a landmine bar at your shoulder
Press it up and forward until your arm is straight
Lower to the shoulder'),
  ('one-handed-bar-hang', 'Grip an overhead bar with one hand and lift your feet
Keep your shoulder engaged and your body still
Switch hands after the set time'),
  ('one-handed-kettlebell-swing', 'Hold a kettlebell in one hand and hike it back between your legs
Snap your hips forward to swing it up to chest height
Let it swing back into the next rep and switch hands after your set'),
  ('one-handed-lat-pulldown', 'Attach a single handle to a high pulley and sit facing the machine
Pull the handle down to your shoulder, driving your elbow toward your side
Let it rise slowly'),
  ('one-legged-leg-extension', 'Sit in the leg extension with the pad on one shin
Straighten that leg fully
Lower slowly and repeat on the other leg'),
  ('one-legged-lying-leg-curl', 'Lie face down on the machine with the pad above one heel
Curl that heel toward your glute
Lower slowly and switch legs'),
  ('one-legged-seated-leg-curl', 'Sit in the machine with one leg on the pad and the thigh pad locked down
Pull your heel down and back under the seat
Return slowly and switch legs'),
  ('overhead-cable-curl', 'Set two cables at a high position and stand between them, holding a handle in each hand with arms out at shoulder height
Curl the handles toward your head while your upper arms stay level
Straighten slowly'),
  ('overhead-cable-triceps-extension', 'Attach a rope to a low pulley and face away from the stack, holding the rope behind your head
With your elbows pointing up, extend your arms overhead
Return slowly'),
  ('overhead-cable-triceps-extension-upper-position', 'Attach a rope to a high pulley and face away from it with a slight forward lean, holding the rope behind your head
Keep your elbows by your ears and straighten your arms forward
Bend them back slowly'),
  ('overhead-press', 'Stand with the bar at your front shoulders and hands just outside shoulder width
Brace and press it straight up, moving your head back slightly as it passes
Lock out overhead and lower to your shoulders'),
  ('pallof-press', 'Stand side-on to a cable or band at chest height, holding the handle at your chest
Press it straight out in front of you and resist being pulled toward the anchor
Bring it back and repeat, then switch sides'),
  ('pause-deadlift', 'Deadlift the bar from the floor and pause for a moment just below your knees
Keep your back flat during the pause, then finish standing tall
Lower with control'),
  ('pause-squat', 'Squat to your normal depth and hold the bottom for a set count, staying tight
Drive back up without bouncing'),
  ('pec-deck', 'Sit tall with your back on the pad and forearms or hands on the handles
Bring the handles together in front of your chest
Open them back slowly'),
  ('pendlay-row', 'Hinge until your torso is roughly parallel with the floor and grip the bar at the floor
Row it explosively to your lower chest, then return it to the floor for a dead stop each rep'),
  ('pendulum-squat', 'Stand on the platform with your back against the pad and shoulders under the pads
Lower into a deep squat as the machine swings
Push back up through your feet'),
  ('pin-bench-press', 'Set the safety pins in a power rack just above chest height
Lie under the bar, press it from the pins to lockout, and lower it back to rest on the pins each rep'),
  ('pin-squat', 'Set the safety pins at your chosen depth
Squat down until the bar rests on the pins, pause briefly, then drive back up'),
  ('pistol-squat', 'Stand on one leg with the other straight out in front
Squat down on the standing leg as low as you can while keeping your heel down
Stand back up, holding a support if needed'),
  ('plank', 'Rest on your forearms and toes with elbows under your shoulders
Keep a straight line from head to heels and brace your abs
Hold'),
  ('plank-to-push-up', 'Start in a forearm plank
Press up onto one hand, then the other, into a high plank
Lower back down one arm at a time and alternate the lead arm'),
  ('plank-with-leg-lifts', 'Get into a forearm or high plank
Lift one leg a few inches off the floor, hold briefly and lower
Alternate legs without letting your hips rotate'),
  ('plank-with-shoulder-taps', 'Hold a high plank with feet a little apart
Lift one hand to tap the opposite shoulder, then place it back down
Alternate while keeping your hips still'),
  ('plate-front-raise', 'Hold a weight plate at the sides with both hands in front of your thighs
Raise it to shoulder height with nearly straight arms
Lower slowly'),
  ('plate-pinch', 'Pinch two smooth plates together with their flat sides out, fingers on one side and thumb on the other
Lift them and hold at your side for time
Set them down before your grip slips'),
  ('plate-wrist-curl', 'Sit with your forearm on your thigh, palm up, holding a weight plate with your wrist over your knee
Curl your wrist up, then lower slowly'),
  ('poliquin-raise', 'Stand holding dumbbells with elbows bent at 90 degrees and palms facing in
Raise your elbows out to the sides to shoulder height, then straighten your arms at the top
Bend them again and lower'),
  ('poliquin-step-up', 'Stand on a low step with the heel of your working foot raised on a small wedge or plate
Bend that knee and lower your other foot toward the floor, letting the knee travel forward
Push back up without touching down'),
  ('power-clean', 'Set up over the bar with a grip just outside your legs
Pull it off the floor, extend explosively through your hips and knees, and catch it on your shoulders with your knees only slightly bent
Stand tall'),
  ('power-jerk', 'Hold the bar in the front rack
Dip, drive up hard and push yourself under the bar, catching it overhead with a slight knee bend and feet planted
Stand up'),
  ('power-snatch', 'Take a wide grip with the bar over your mid-foot
Pull it from the floor, extend explosively and catch it overhead on locked arms in a partial squat
Stand up with the bar stable'),
  ('powerlifting-exercises', 'A general entry for the competition lifts: squat, bench press and deadlift
Where possible, log the specific lift instead so your history and records stay accurate'),
  ('preacher-curl', 'Sit at a preacher bench with the backs of your upper arms on the pad, holding a barbell or EZ bar underhand
Curl the bar toward your shoulders
Lower slowly until your arms are nearly straight'),
  ('prisoner-get-up', 'Kneel tall with hands behind your head
Step one foot forward, press through it to stand, then kneel back down one leg at a time
Alternate your lead leg'),
  ('prone-neck-bridge', 'Kneel with your forehead on a padded surface and hands on the floor for support
Gently shift a little weight forward onto your head and roll through a small range
Keep it light, slow and within comfort'),
  ('pull-up', 'Hang from the bar with an overhand grip a little wider than your shoulders
Pull your elbows down until your chin clears the bar
Lower to a full hang'),
  ('pull-ups-with-a-neutral-grip', 'Hang from parallel handles with palms facing each other
Pull until your chin clears the handles
Lower under control'),
  ('push-press', 'Hold the bar across your front shoulders
Dip slightly at the knees, then drive up and use that leg drive to press the bar overhead to lockout
Lower it to your shoulders'),
  ('push-up', 'Set your hands slightly wider than your shoulders and your body straight from head to heels
Lower your chest to just above the floor with elbows angled back
Push back up'),
  ('push-up-against-wall', 'Stand arm''s length from a wall and place your hands on it at shoulder height
Bend your elbows to bring your chest toward the wall, then push back
Keep your body straight'),
  ('push-ups-with-feet-in-rings', 'Place your feet in rings or suspension straps hanging a few inches off the floor and get into a push-up position
Lower your chest while keeping your body rigid
Push back up'),
  ('rack-pull', 'Set the bar on pins or blocks around knee height
Grip it, brace and stand up by driving your hips forward
Lower it back to the pins with control'),
  ('renegade-row', 'Get into a high plank with hands on two dumbbells and feet wide
Row one dumbbell to your hip without rotating your hips
Set it down and switch sides'),
  ('resistance-band-chest-fly', 'Anchor a band behind you at chest height and hold an end in each hand with arms out to the sides
Bring your hands together in front of your chest with a slight elbow bend
Open back out slowly'),
  ('resistance-band-curl', 'Stand on the middle of a band and hold the ends with palms forward
Curl your hands toward your shoulders with elbows at your sides
Lower slowly'),
  ('resistance-band-lateral-raise', 'Stand on the middle of a band holding an end in each hand at your sides
Raise your arms out to shoulder height with a slight bend in the elbows
Lower slowly'),
  ('reverse-barbell-curl', 'Hold a barbell with an overhand grip at shoulder width
Curl it up with your elbows at your sides and wrists straight
Lower slowly'),
  ('reverse-barbell-lunge', 'With a barbell on your upper back, step one foot back and lower until your back knee nearly touches the floor
Push through your front foot to bring the back leg forward to standing
Alternate legs'),
  ('reverse-body-weight-lunges', 'Stand tall with hands on your hips
Step one foot back and bend both knees until the back knee hovers above the floor
Drive through your front foot to return and switch legs'),
  ('reverse-dumbbell-curl', 'Hold dumbbells at your sides with palms facing back
Curl them up while keeping that overhand grip and elbows tucked
Lower slowly'),
  ('reverse-fly', 'Hinge forward with a flat back holding light dumbbells below your chest
With a slight bend in your elbows, raise your arms out to the sides until they line up with your shoulders
Lower slowly'),
  ('reverse-dumbbell-flyes-on-incline-bench', 'Lie face down on an incline bench holding dumbbells below you
Raise your arms out to the sides with slightly bent elbows until level with your shoulders
Lower under control'),
  ('reverse-dumbbell-lunge', 'Hold dumbbells at your sides
Step back and lower until your back knee is just above the floor
Push through the front foot to return and alternate legs'),
  ('reverse-hyperextension', 'Lie face down on the machine or a high bench with your hips at the edge and legs hanging
Hold on, then lift your legs up behind you until they line up with your torso
Lower them slowly without swinging'),
  ('reverse-machine-fly', 'Sit facing the pec deck pad with the handles set to the rear position
Holding the handles with slightly bent arms, pull them out and back until your arms line up with your shoulders
Return slowly'),
  ('reverse-nordic', 'Kneel upright with your shins on a pad and your body straight from knees to head
Lean back slowly by bending at the knees, keeping your hips straight
Go as far as you can control, then pull yourself back upright'),
  ('ring-dip', 'Support yourself on rings with straight arms and the rings close to your body
Lower until your shoulders are just below your elbows, keeping the rings steady
Press back up and turn your palms slightly forward at the top'),
  ('ring-pull-up', 'Hang from rings with arms straight
Pull yourself up until your chin passes your hands, letting the rings turn naturally
Lower under control'),
  ('ring-row', 'Set the rings around waist height and lean back holding them with straight arms and a rigid body
Pull your chest up toward your hands
Lower slowly
Walk your feet forward to make it harder'),
  ('romanian-deadlift', 'Stand holding the bar at your thighs with soft knees
Push your hips back and slide the bar down your legs until you feel a strong hamstring stretch, keeping your back flat
Drive your hips forward to stand'),
  ('rope-lat-pulldown', 'Attach a rope to a high pulley and kneel or sit facing it
Pull the rope down toward your upper chest, spreading the ends and driving your elbows down
Let it rise slowly'),
  ('rowing-machine', 'Sit on the rower with feet strapped in and hold the handle
Push with your legs first, then lean back slightly and pull the handle to your lower ribs
Reverse the order to return'),
  ('safety-bar-squat', 'Set the safety squat bar on your upper back and hold the handles in front
Brace, walk out and squat down with your chest up
Drive back up through your whole foot'),
  ('scap-pull-up', 'Hang from a bar with straight arms
Without bending your elbows, pull your shoulder blades down and together to lift your body slightly
Relax back to a full hang'),
  ('seal-row', 'Lie face down on a raised bench with a barbell or dumbbells below you
Row the weight up to the underside of the bench
Lower until your arms are straight'),
  ('seated-barbell-overhead-press', 'Sit on a bench with back support and the bar at your front shoulders
Press it straight overhead until your arms lock
Lower back to your shoulders'),
  ('seated-cable-chest-fly', 'Sit on a bench between two cables set at chest height, handles in hand and arms out wide
Bring your hands together in front of your chest with a slight bend in the elbows
Open back out slowly'),
  ('seated-row', 'Sit at a cable row with feet on the platform and knees soft, holding a close-grip handle
Pull it to your stomach while sitting tall and squeezing your shoulder blades
Let your arms extend without rounding forward'),
  ('seated-calf-raise', 'Sit in the machine with the pad over your lower thighs and the balls of your feet on the platform
Drop your heels for a stretch, then push up onto your toes
Pause and lower'),
  ('dumbbell-ohp', 'Sit on a bench with back support holding dumbbells at shoulder height
Press them up until your arms are straight overhead
Lower back to your shoulders'),
  ('seated-kettlebell-press', 'Sit tall on a bench or the floor with a kettlebell in the rack position
Press it overhead to a locked arm
Lower slowly back to your shoulder'),
  ('seated-leg-curl', 'Sit in the machine with the pad behind your lower calves and the thigh pad locked down
Pull your heels down and under the seat
Return slowly'),
  ('shallow-lunges-bodyweight', 'Stand tall and step forward into a short, partial lunge, bending your knees only part of the way
Press through your front foot to return and alternate legs'),
  ('side-lunges-bodyweight', 'Stand with feet together
Take a wide step out to one side and sit your hips back over that foot, keeping the other leg straight
Push back to center and alternate'),
  ('side-plank', 'Lie on your side and prop yourself on your forearm with elbow under your shoulder
Lift your hips so your body is straight from head to feet
Hold, then switch sides'),
  ('single-leg-deadlift-with-kettlebell', 'Stand on one leg holding a kettlebell in the opposite hand
Hinge at the hip and let your free leg rise behind you until your torso is near horizontal
Stand back up and switch sides after your reps'),
  ('one-handed-cable-row', 'Attach a single handle to a cable at about chest height
Pull it toward your side, driving your elbow back without twisting your torso
Straighten your arm slowly and switch sides'),
  ('one-legged-hip-thrust', 'Set up for a hip thrust with your upper back on a bench and one foot planted, the other leg lifted
Drive through the planted heel to lift your hips
Lower and switch sides after your reps'),
  ('single-leg-romanian-deadlift', 'Stand on one leg with a soft knee, holding weights if you like
Hinge forward at the hip as your free leg reaches back, keeping your hips square
Return to standing'),
  ('sit-up', 'Lie on your back with knees bent and feet flat or anchored
Curl your torso all the way up until your chest is near your thighs
Lower slowly'),
  ('smith-machine-bench-press', 'Set a flat bench under the Smith bar so it lines up with your mid-chest
Unhook the bar, lower it to your chest, and press back up
Rehook it at the end of the set'),
  ('smith-machine-bulgarian-split-squat', 'Place a bench behind the Smith machine and set the bar on your upper back
Rest your back foot on the bench and lower until your front thigh is about parallel
Push up through your front foot'),
  ('smith-machine-calf-raise', 'Stand under the Smith bar with the balls of your feet on a plate or step
Unhook the bar, lower your heels for a stretch, then rise onto your toes
Pause and lower'),
  ('smith-machine-close-grip-bench-press', 'Lie under the Smith bar and grip it at shoulder width
Lower it to your lower chest with elbows tucked
Press back up'),
  ('smith-machine-deadlift', 'Set the Smith bar low and stand close with it over your mid-foot
Grip it, flatten your back and stand up
Lower it to the start under control'),
  ('smith-machine-decline-bench-press', 'Set a decline bench under the Smith bar and secure your legs
Unhook the bar, lower it to your lower chest and press it back up'),
  ('smith-machine-front-squat', 'Rest the Smith bar on the front of your shoulders with elbows high
Unhook it and squat down with your torso upright
Drive back up'),
  ('smith-machine-hip-thrust', 'Sit with your upper back on a bench and the padded Smith bar over your hips
Unhook it and drive your hips up until your body is flat from shoulders to knees
Lower under control'),
  ('smith-machine-incline-bench-press', 'Set an incline bench under the Smith bar so it meets your upper chest
Unhook, lower the bar to your upper chest and press up'),
  ('smith-machine-landmine-press', 'Set the Smith bar at shoulder height and stand facing it in a split stance
Hold it at your shoulder and press up along the track until your arm is straight
Lower slowly
Keep the load moderate'),
  ('smith-machine-lunge', 'Set the Smith bar on your upper back and take a split stance
Lower straight down until your back knee nearly touches the floor, then press back up
Switch legs after your reps'),
  ('smith-machine-one-handed-row', 'Set the Smith bar at about knee height and stand beside it
Hinge forward, grip the middle of the bar with one hand and row it toward your hip
Lower and switch sides after your reps'),
  ('smith-machine-reverse-grip-bench-press', 'Lie under the Smith bar and grip it with palms facing you at about shoulder width
Lower it to your lower chest and press back up
Use a light load to start'),
  ('smith-machine-romanian-deadlift', 'Stand holding the Smith bar at your thighs with soft knees
Hinge your hips back to lower the bar until your hamstrings stretch, keeping your back flat
Drive your hips forward to stand'),
  ('smith-machine-shrug', 'Stand holding the Smith bar in front of your thighs
Lift your shoulders straight up toward your ears and pause
Lower fully'),
  ('seated-smith-machine-shoulder-press', 'Set an upright bench under the Smith bar so it lines up in front of your face
Unhook and press the bar overhead
Lower to about chin level'),
  ('smith-machine-skull-crushers', 'Lie on a bench under the Smith bar with a narrow grip and arms straight
Bend your elbows to lower the bar toward your forehead
Extend back up'),
  ('smith-machine-squat', 'Set the Smith bar on your upper back with feet slightly in front of you
Unhook and squat down until your thighs are about parallel
Drive back up'),
  ('snatch', 'Take a wide grip with the bar over your mid-foot
Lift it from the floor, extend explosively and pull yourself under, catching the bar overhead in a full squat
Stand up with it locked out'),
  ('snatch-grip-behind-the-neck-press', 'Hold the bar on your upper back with a wide snatch grip
Press it straight up to lockout
Lower back to your shoulders
Use light weights and a comfortable range'),
  ('snatch-grip-deadlift', 'Take a wide snatch grip with the bar over your mid-foot
Lower your hips, flatten your back and stand up
Lower with control'),
  ('spider-curl', 'Lie chest-down on an incline bench with your arms hanging straight down
Curl the weights up toward your shoulders without moving your upper arms
Lower slowly'),
  ('split-jerk', 'Hold the bar in the front rack
Dip and drive, then split your feet forward and back as you push under the bar to catch it on locked arms
Step your feet together to finish'),
  ('squat-jerk', 'Hold the bar in the front rack
Dip and drive the bar up, then drop into a full squat to catch it on locked arms
Stand up with the bar overhead'),
  ('cable-fly', 'Set two cables high and stand between them in a split stance, handles in hand
Bring your hands together in front of your chest in a hugging arc with slightly bent elbows
Open back out slowly'),
  ('standing-cable-leg-extension', 'Attach an ankle strap to a low cable and face away from it
Holding a support, bend the strapped knee behind you, then straighten it to extend your leg
Return slowly'),
  ('calf-raise', 'Stand in the machine with the pads on your shoulders and the balls of your feet on the platform
Drop your heels for a stretch, then rise as high as you can
Pause and lower'),
  ('dumbbell-horizontal-external-shoulder-rotation', 'Stand holding a light dumbbell with your upper arm out to the side at shoulder height and elbow bent at 90 degrees, forearm pointing forward
Rotate your forearm up until it points to the ceiling
Lower slowly'),
  ('dumbbell-shoulder-press', 'Stand holding dumbbells at shoulder height
Press them overhead until your arms are straight
Lower them back to your shoulders'),
  ('standing-glute-kickback-in-machine', 'Stand in the machine with the pad against the back of your working leg
Press the leg back by squeezing your glute
Return slowly and switch sides after your reps'),
  ('standing-glute-push-down', 'Stand on the step of an assisted dip or pull-up machine and place one foot on the knee pad
Holding the handles, push the pad down by extending your hip
Let it rise slowly and switch legs'),
  ('standing-hip-abduction-against-band', 'Stand with a mini band around your ankles and hold a support
Lift one leg out to the side against the band without leaning
Return slowly and switch sides'),
  ('standing-hip-flexor-raise', 'Stand on a low step on one leg with a light weight or band on the other foot
Lift that knee up toward your chest while standing tall
Lower slowly and switch sides after your reps'),
  ('standing-leg-curl', 'Stand in the machine with the pad behind your lower leg
Curl your heel toward your glute
Lower slowly and switch legs'),
  ('standing-resistance-band-chest-fly', 'Anchor a band behind you at chest height and hold an end in each hand in a split stance
Bring your arms together in front of your chest with a slight elbow bend
Open back out slowly'),
  ('stationary-bike', 'Adjust the seat so your knee is slightly bent at the bottom of the pedal stroke
Pedal at a steady cadence and set the resistance to match your planned effort'),
  ('step-up', 'Stand facing a box or bench with a foot on top
Drive through that foot to step up until you are standing tall on the box
Step down slowly and alternate legs'),
  ('stiff-legged-deadlift', 'Stand holding the bar with your legs nearly straight
Hinge at your hips to lower the bar toward the floor with a flat back
Stand back up by driving your hips forward'),
  ('straight-arm-lat-pulldown', 'Face a high pulley holding a bar or rope with straight arms
Push it down in an arc toward your thighs, keeping your elbows locked
Let it rise slowly to eye level'),
  ('sumo-deadlift', 'Take a wide stance with toes turned out and grip the bar inside your legs
Push your knees out, flatten your back and stand up
Lower the bar with control'),
  ('sumo-squat', 'Stand with a wide stance, toes turned out, holding a dumbbell or kettlebell between your legs
Squat down with your chest up and knees pushing out
Stand back up'),
  ('superman-raise', 'Lie face down with arms stretched overhead
Lift your arms, chest and legs a few inches off the floor
Hold briefly and lower'),
  ('supine-neck-bridge', 'Lie on your back with knees bent and a pad under your head
Press the back of your head gently into the pad to lift your shoulders slightly
Lower slowly
Keep the range small'),
  ('t-bar-row', 'Straddle the T-bar or landmine and grip the handle
Hinge forward with a flat back and row the weight toward your chest
Lower with control'),
  ('tate-press', 'Lie on a bench with dumbbells over your chest, palms facing your feet
Bend your elbows out to the sides to lower the dumbbells toward your chest
Extend back up'),
  ('tibialis-band-pull', 'Sit with your legs straight and a band anchored in front of you, looped over the top of one foot
Pull your toes toward your shin against the band
Return slowly and switch feet'),
  ('tibialis-raise', 'Stand with your back against a wall and your heels about a foot out
Lift your toes as high as you can, then lower them slowly'),
  ('towel-pull-up', 'Loop two towels over a pull-up bar and grip one in each hand
Pull yourself up until your chin reaches your hands
Lower slowly to a full hang'),
  ('towel-row', 'Wrap a towel around a sturdy post or anchor and hold an end in each hand
Lean back with a straight body, then row your chest toward your hands
Lower slowly'),
  ('trap-bar-deadlift-with-low-handles', 'Stand inside the trap bar and grip the low handles
Brace, flatten your back and push through the floor to stand up
Lower with control'),
  ('trap-bar-deadlift-with-high-handles', 'Stand inside the trap bar and grip the raised handles
Brace and stand up by driving through your feet
Lower back to the floor'),
  ('tricep-press', 'Sit in the machine with the thigh pad secured and grip the handles at chest height
Press the handles down until your elbows are straight, keeping them close to your sides
Let them rise slowly'),
  ('tricep-pushdown-with-bar', 'Face a high pulley with a straight or angled bar at chest height
Keeping your elbows at your sides, push the bar down until your arms are straight
Let it rise slowly'),
  ('tricep-pushdown', 'Face a high pulley holding a rope with thumbs up and elbows at your sides
Push the rope down and spread the ends at the bottom
Let it rise slowly'),
  ('turkish-get-up', 'Lie on your back holding a kettlebell straight up in one hand, same-side knee bent
Roll onto your opposite elbow, then hand, lift your hips and sweep your leg under into a kneel, then stand
Reverse each step to lie down, keeping your eyes on the kettlebell'),
  ('upright-row', 'Stand holding a barbell with a grip a bit narrower than shoulder width
Pull it up along your body, leading with your elbows, until they reach about shoulder height
Lower slowly'),
  ('vertical-leg-press', 'Lie under the vertical leg press with your feet on the platform
Release the lock and lower the platform until your knees are well bent
Press it back up'),
  ('wall-walk', 'Start in a high plank with your feet against a wall
Walk your feet up the wall as your hands walk back until you are near vertical
Walk back down the same way'),
  ('weighted-plank', 'Get into a forearm plank and have a partner place a plate on your upper back
Hold a straight line from head to heels with your abs braced
Have the plate removed before you come down'),
  ('wrist-roller', 'Hold the wrist roller at shoulder height with straight arms and a light weight hanging from it
Roll the rope up by turning your wrists one at a time
Unroll it slowly'),
  ('z-press', 'Sit on the floor with your legs straight and the bar at your front shoulders
Press it straight overhead, keeping your torso upright
Lower back to your shoulders'),
  ('zercher-squat', 'Set the bar in a rack at about waist height and cradle it in the crooks of your elbows
Brace and squat down with your torso upright
Drive back up'),
  ('zombie-squat', 'Rest the bar on the front of your shoulders and hold your arms straight out in front of you
Squat down with your torso upright and elbows high
Stand back up'),
  ('zottman-curl', 'Hold dumbbells at your sides with palms forward
Curl them up, then rotate your palms down at the top
Lower slowly with that overhand grip, then rotate back')
) as v(id, instructions)
where c.id = v.id
  and c.instructions is distinct from v.instructions;
